// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: historian/historian.proto

package historian

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log_Level int32

const (
	Log_PANIC   Log_Level = 0
	Log_FATAL   Log_Level = 1
	Log_ERROR   Log_Level = 2
	Log_WARNING Log_Level = 3
	Log_INFO    Log_Level = 4
	Log_DEBUG   Log_Level = 5
	Log_TRACE   Log_Level = 6
)

// Enum value maps for Log_Level.
var (
	Log_Level_name = map[int32]string{
		0: "PANIC",
		1: "FATAL",
		2: "ERROR",
		3: "WARNING",
		4: "INFO",
		5: "DEBUG",
		6: "TRACE",
	}
	Log_Level_value = map[string]int32{
		"PANIC":   0,
		"FATAL":   1,
		"ERROR":   2,
		"WARNING": 3,
		"INFO":    4,
		"DEBUG":   5,
		"TRACE":   6,
	}
)

func (x Log_Level) Enum() *Log_Level {
	p := new(Log_Level)
	*p = x
	return p
}

func (x Log_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Log_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_historian_historian_proto_enumTypes[0].Descriptor()
}

func (Log_Level) Type() protoreflect.EnumType {
	return &file_historian_historian_proto_enumTypes[0]
}

func (x Log_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Log_Level.Descriptor instead.
func (Log_Level) EnumDescriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{10, 0}
}

type CollectorHA struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MainCollectorUUID string                 `protobuf:"bytes,1,opt,name=mainCollectorUUID,proto3" json:"mainCollectorUUID,omitempty"`
	Host              string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	HealthPort        int32                  `protobuf:"varint,3,opt,name=healthPort,proto3" json:"healthPort,omitempty"`
	Timeout           int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	StopDelay         int32                  `protobuf:"varint,5,opt,name=stopDelay,proto3" json:"stopDelay,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CollectorHA) Reset() {
	*x = CollectorHA{}
	mi := &file_historian_historian_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorHA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorHA) ProtoMessage() {}

func (x *CollectorHA) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorHA.ProtoReflect.Descriptor instead.
func (*CollectorHA) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{0}
}

func (x *CollectorHA) GetMainCollectorUUID() string {
	if x != nil {
		return x.MainCollectorUUID
	}
	return ""
}

func (x *CollectorHA) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CollectorHA) GetHealthPort() int32 {
	if x != nil {
		return x.HealthPort
	}
	return 0
}

func (x *CollectorHA) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CollectorHA) GetStopDelay() int32 {
	if x != nil {
		return x.StopDelay
	}
	return 0
}

type Collector struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Buildversion    string                 `protobuf:"bytes,3,opt,name=buildversion,proto3" json:"buildversion,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Settings        *structpb.Struct       `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	HaSettings      *CollectorHA           `protobuf:"bytes,7,opt,name=haSettings,proto3" json:"haSettings,omitempty"`
	BuildOs         string                 `protobuf:"bytes,8,opt,name=buildOs,proto3" json:"buildOs,omitempty"`
	BuildArch       string                 `protobuf:"bytes,9,opt,name=buildArch,proto3" json:"buildArch,omitempty"`
	UpdateAvailable bool                   `protobuf:"varint,10,opt,name=updateAvailable,proto3" json:"updateAvailable,omitempty"`
	UpdateToVersion string                 `protobuf:"bytes,11,opt,name=updateToVersion,proto3" json:"updateToVersion,omitempty"`
	State           *structpb.Struct       `protobuf:"bytes,12,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Collector) Reset() {
	*x = Collector{}
	mi := &file_historian_historian_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collector) ProtoMessage() {}

func (x *Collector) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collector.ProtoReflect.Descriptor instead.
func (*Collector) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{1}
}

func (x *Collector) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Collector) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Collector) GetBuildversion() string {
	if x != nil {
		return x.Buildversion
	}
	return ""
}

func (x *Collector) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Collector) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Collector) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Collector) GetHaSettings() *CollectorHA {
	if x != nil {
		return x.HaSettings
	}
	return nil
}

func (x *Collector) GetBuildOs() string {
	if x != nil {
		return x.BuildOs
	}
	return ""
}

func (x *Collector) GetBuildArch() string {
	if x != nil {
		return x.BuildArch
	}
	return ""
}

func (x *Collector) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *Collector) GetUpdateToVersion() string {
	if x != nil {
		return x.UpdateToVersion
	}
	return ""
}

func (x *Collector) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

type RegisterCollectorSchema struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CollectorType             string                 `protobuf:"bytes,1,opt,name=collectorType,proto3" json:"collectorType,omitempty"`
	BuildVersion              string                 `protobuf:"bytes,2,opt,name=buildVersion,proto3" json:"buildVersion,omitempty"`
	MeasurementSettingsSchema *structpb.Struct       `protobuf:"bytes,3,opt,name=measurementSettingsSchema,proto3" json:"measurementSettingsSchema,omitempty"`
	SettingsSchema            *structpb.Struct       `protobuf:"bytes,4,opt,name=settingsSchema,proto3" json:"settingsSchema,omitempty"`
	BuildOs                   string                 `protobuf:"bytes,5,opt,name=buildOs,proto3" json:"buildOs,omitempty"`
	BuildArch                 string                 `protobuf:"bytes,6,opt,name=buildArch,proto3" json:"buildArch,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RegisterCollectorSchema) Reset() {
	*x = RegisterCollectorSchema{}
	mi := &file_historian_historian_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCollectorSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCollectorSchema) ProtoMessage() {}

func (x *RegisterCollectorSchema) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCollectorSchema.ProtoReflect.Descriptor instead.
func (*RegisterCollectorSchema) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterCollectorSchema) GetCollectorType() string {
	if x != nil {
		return x.CollectorType
	}
	return ""
}

func (x *RegisterCollectorSchema) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *RegisterCollectorSchema) GetMeasurementSettingsSchema() *structpb.Struct {
	if x != nil {
		return x.MeasurementSettingsSchema
	}
	return nil
}

func (x *RegisterCollectorSchema) GetSettingsSchema() *structpb.Struct {
	if x != nil {
		return x.SettingsSchema
	}
	return nil
}

func (x *RegisterCollectorSchema) GetBuildOs() string {
	if x != nil {
		return x.BuildOs
	}
	return ""
}

func (x *RegisterCollectorSchema) GetBuildArch() string {
	if x != nil {
		return x.BuildArch
	}
	return ""
}

type Point struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MeasurementUUID string                 `protobuf:"bytes,1,opt,name=measurementUUID,proto3" json:"measurementUUID,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value           *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Tags            *structpb.Struct       `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_historian_historian_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{3}
}

func (x *Point) GetMeasurementUUID() string {
	if x != nil {
		return x.MeasurementUUID
	}
	return ""
}

func (x *Point) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Point) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Point) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Point) GetTags() *structpb.Struct {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Used to send batches of points over the stream and to marshal a batch of points to file
type Points struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Points) Reset() {
	*x = Points{}
	mi := &file_historian_historian_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Points) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Points) ProtoMessage() {}

func (x *Points) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Points.ProtoReflect.Descriptor instead.
func (*Points) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{4}
}

func (x *Points) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

// Provide an empty message instead of using default empty message if we want to add
// something in the future
type CreatePointsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePointsReply) Reset() {
	*x = CreatePointsReply{}
	mi := &file_historian_historian_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePointsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePointsReply) ProtoMessage() {}

func (x *CreatePointsReply) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePointsReply.ProtoReflect.Descriptor instead.
func (*CreatePointsReply) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{5}
}

type Measurement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Settings         *structpb.Struct       `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	Datatype         string                 `protobuf:"bytes,7,opt,name=datatype,proto3" json:"datatype,omitempty"`
	EngineeringSpecs *EngineeringSpecs      `protobuf:"bytes,8,opt,name=engineeringSpecs,proto3" json:"engineeringSpecs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	mi := &file_historian_historian_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{6}
}

func (x *Measurement) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Measurement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Measurement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Measurement) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Measurement) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Measurement) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Measurement) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *Measurement) GetEngineeringSpecs() *EngineeringSpecs {
	if x != nil {
		return x.EngineeringSpecs
	}
	return nil
}

type EngineeringSpecs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uom           *string                `protobuf:"bytes,1,opt,name=uom,proto3,oneof" json:"uom,omitempty"`
	ValueMin      *float64               `protobuf:"fixed64,2,opt,name=valueMin,proto3,oneof" json:"valueMin,omitempty"`
	ValueMax      *float64               `protobuf:"fixed64,3,opt,name=valueMax,proto3,oneof" json:"valueMax,omitempty"`
	LimitLo       *float64               `protobuf:"fixed64,4,opt,name=limitLo,proto3,oneof" json:"limitLo,omitempty"`
	LimitHi       *float64               `protobuf:"fixed64,5,opt,name=limitHi,proto3,oneof" json:"limitHi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineeringSpecs) Reset() {
	*x = EngineeringSpecs{}
	mi := &file_historian_historian_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineeringSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineeringSpecs) ProtoMessage() {}

func (x *EngineeringSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineeringSpecs.ProtoReflect.Descriptor instead.
func (*EngineeringSpecs) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{7}
}

func (x *EngineeringSpecs) GetUom() string {
	if x != nil && x.Uom != nil {
		return *x.Uom
	}
	return ""
}

func (x *EngineeringSpecs) GetValueMin() float64 {
	if x != nil && x.ValueMin != nil {
		return *x.ValueMin
	}
	return 0
}

func (x *EngineeringSpecs) GetValueMax() float64 {
	if x != nil && x.ValueMax != nil {
		return *x.ValueMax
	}
	return 0
}

func (x *EngineeringSpecs) GetLimitLo() float64 {
	if x != nil && x.LimitLo != nil {
		return *x.LimitLo
	}
	return 0
}

func (x *EngineeringSpecs) GetLimitHi() float64 {
	if x != nil && x.LimitHi != nil {
		return *x.LimitHi
	}
	return 0
}

type MeasurementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	CollectorUUID string                 `protobuf:"bytes,2,opt,name=collectorUUID,proto3" json:"collectorUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementRequest) Reset() {
	*x = MeasurementRequest{}
	mi := &file_historian_historian_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementRequest) ProtoMessage() {}

func (x *MeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementRequest.ProtoReflect.Descriptor instead.
func (*MeasurementRequest) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{8}
}

func (x *MeasurementRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *MeasurementRequest) GetCollectorUUID() string {
	if x != nil {
		return x.CollectorUUID
	}
	return ""
}

type Measurements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Measurements  []*Measurement         `protobuf:"bytes,1,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Measurements) Reset() {
	*x = Measurements{}
	mi := &file_historian_historian_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurements) ProtoMessage() {}

func (x *Measurements) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurements.ProtoReflect.Descriptor instead.
func (*Measurements) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{9}
}

func (x *Measurements) GetMeasurements() []*Measurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type Log struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Message   *structpb.Struct       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level     Log_Level              `protobuf:"varint,2,opt,name=level,proto3,enum=proto.Log_Level" json:"level,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Deprecated: Marked as deprecated in historian/historian.proto.
	Health          string `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	MeasurementUUID string `protobuf:"bytes,5,opt,name=measurementUUID,proto3" json:"measurementUUID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_historian_historian_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{10}
}

func (x *Log) GetMessage() *structpb.Struct {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Log) GetLevel() Log_Level {
	if x != nil {
		return x.Level
	}
	return Log_PANIC
}

func (x *Log) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Deprecated: Marked as deprecated in historian/historian.proto.
func (x *Log) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *Log) GetMeasurementUUID() string {
	if x != nil {
		return x.MeasurementUUID
	}
	return ""
}

type Logs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*Log                 `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logs) Reset() {
	*x = Logs{}
	mi := &file_historian_historian_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logs) ProtoMessage() {}

func (x *Logs) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logs.ProtoReflect.Descriptor instead.
func (*Logs) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{11}
}

func (x *Logs) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type CreateLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLogsReply) Reset() {
	*x = CreateLogsReply{}
	mi := &file_historian_historian_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogsReply) ProtoMessage() {}

func (x *CreateLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogsReply.ProtoReflect.Descriptor instead.
func (*CreateLogsReply) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{12}
}

type Statistics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System statistics
	SystemUptime        float64 `protobuf:"fixed64,1,opt,name=systemUptime,proto3" json:"systemUptime,omitempty"` // As time.Duration seconds
	SystemCPUUsage      float64 `protobuf:"fixed64,2,opt,name=systemCPUUsage,proto3" json:"systemCPUUsage,omitempty"`
	SystemMemoryUsage   float64 `protobuf:"fixed64,3,opt,name=systemMemoryUsage,proto3" json:"systemMemoryUsage,omitempty"`
	SystemFreeDiskSpace int64   `protobuf:"varint,4,opt,name=systemFreeDiskSpace,proto3" json:"systemFreeDiskSpace,omitempty"`
	// Collector statistics
	CollectorUptime     float64 `protobuf:"fixed64,5,opt,name=collectorUptime,proto3" json:"collectorUptime,omitempty"` // As time.Duration seconds
	CollectorPointsSent int64   `protobuf:"varint,6,opt,name=collectorPointsSent,proto3" json:"collectorPointsSent,omitempty"`
	CollectorGoodPoints int64   `protobuf:"varint,7,opt,name=collectorGoodPoints,proto3" json:"collectorGoodPoints,omitempty"`
	CollectorBadPoints  int64   `protobuf:"varint,8,opt,name=collectorBadPoints,proto3" json:"collectorBadPoints,omitempty"`
	// Buffer statistics
	BufferCurrentSize int64 `protobuf:"varint,9,opt,name=bufferCurrentSize,proto3" json:"bufferCurrentSize,omitempty"`
	BufferDiskFlushes int64 `protobuf:"varint,10,opt,name=bufferDiskFlushes,proto3" json:"bufferDiskFlushes,omitempty"`
	BufferErrorFiles  int64 `protobuf:"varint,11,opt,name=bufferErrorFiles,proto3" json:"bufferErrorFiles,omitempty"`
	// Other statistics
	Other     *structpb.Struct       `protobuf:"bytes,12,opt,name=other,proto3" json:"other,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Extra system statistics
	SystemTotalDiskSpace int64 `protobuf:"varint,14,opt,name=systemTotalDiskSpace,proto3" json:"systemTotalDiskSpace,omitempty"`
	SystemMemoryFree     int64 `protobuf:"varint,15,opt,name=systemMemoryFree,proto3" json:"systemMemoryFree,omitempty"`
	SystemMemoryTotal    int64 `protobuf:"varint,16,opt,name=systemMemoryTotal,proto3" json:"systemMemoryTotal,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_historian_historian_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{13}
}

func (x *Statistics) GetSystemUptime() float64 {
	if x != nil {
		return x.SystemUptime
	}
	return 0
}

func (x *Statistics) GetSystemCPUUsage() float64 {
	if x != nil {
		return x.SystemCPUUsage
	}
	return 0
}

func (x *Statistics) GetSystemMemoryUsage() float64 {
	if x != nil {
		return x.SystemMemoryUsage
	}
	return 0
}

func (x *Statistics) GetSystemFreeDiskSpace() int64 {
	if x != nil {
		return x.SystemFreeDiskSpace
	}
	return 0
}

func (x *Statistics) GetCollectorUptime() float64 {
	if x != nil {
		return x.CollectorUptime
	}
	return 0
}

func (x *Statistics) GetCollectorPointsSent() int64 {
	if x != nil {
		return x.CollectorPointsSent
	}
	return 0
}

func (x *Statistics) GetCollectorGoodPoints() int64 {
	if x != nil {
		return x.CollectorGoodPoints
	}
	return 0
}

func (x *Statistics) GetCollectorBadPoints() int64 {
	if x != nil {
		return x.CollectorBadPoints
	}
	return 0
}

func (x *Statistics) GetBufferCurrentSize() int64 {
	if x != nil {
		return x.BufferCurrentSize
	}
	return 0
}

func (x *Statistics) GetBufferDiskFlushes() int64 {
	if x != nil {
		return x.BufferDiskFlushes
	}
	return 0
}

func (x *Statistics) GetBufferErrorFiles() int64 {
	if x != nil {
		return x.BufferErrorFiles
	}
	return 0
}

func (x *Statistics) GetOther() *structpb.Struct {
	if x != nil {
		return x.Other
	}
	return nil
}

func (x *Statistics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Statistics) GetSystemTotalDiskSpace() int64 {
	if x != nil {
		return x.SystemTotalDiskSpace
	}
	return 0
}

func (x *Statistics) GetSystemMemoryFree() int64 {
	if x != nil {
		return x.SystemMemoryFree
	}
	return 0
}

func (x *Statistics) GetSystemMemoryTotal() int64 {
	if x != nil {
		return x.SystemMemoryTotal
	}
	return 0
}

type CreateStatisticsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStatisticsReply) Reset() {
	*x = CreateStatisticsReply{}
	mi := &file_historian_historian_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStatisticsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStatisticsReply) ProtoMessage() {}

func (x *CreateStatisticsReply) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStatisticsReply.ProtoReflect.Descriptor instead.
func (*CreateStatisticsReply) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{14}
}

type CreateMeasurementsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeasurementsReply) Reset() {
	*x = CreateMeasurementsReply{}
	mi := &file_historian_historian_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeasurementsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeasurementsReply) ProtoMessage() {}

func (x *CreateMeasurementsReply) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeasurementsReply.ProtoReflect.Descriptor instead.
func (*CreateMeasurementsReply) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{15}
}

type CreateMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      *string                `protobuf:"bytes,2,opt,name=dataType,proto3,oneof" json:"dataType,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AutoOnboard   bool                   `protobuf:"varint,4,opt,name=autoOnboard,proto3" json:"autoOnboard,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,5,opt,name=attributes,proto3,oneof" json:"attributes,omitempty"`
	Settings      *structpb.Struct       `protobuf:"bytes,6,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeasurement) Reset() {
	*x = CreateMeasurement{}
	mi := &file_historian_historian_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeasurement) ProtoMessage() {}

func (x *CreateMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeasurement.ProtoReflect.Descriptor instead.
func (*CreateMeasurement) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{16}
}

func (x *CreateMeasurement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMeasurement) GetDataType() string {
	if x != nil && x.DataType != nil {
		return *x.DataType
	}
	return ""
}

func (x *CreateMeasurement) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateMeasurement) GetAutoOnboard() bool {
	if x != nil {
		return x.AutoOnboard
	}
	return false
}

func (x *CreateMeasurement) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateMeasurement) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CreateMeasurementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Measurements  []*CreateMeasurement   `protobuf:"bytes,1,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeasurementsRequest) Reset() {
	*x = CreateMeasurementsRequest{}
	mi := &file_historian_historian_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeasurementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeasurementsRequest) ProtoMessage() {}

func (x *CreateMeasurementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeasurementsRequest.ProtoReflect.Descriptor instead.
func (*CreateMeasurementsRequest) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{17}
}

func (x *CreateMeasurementsRequest) GetMeasurements() []*CreateMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type CollectorUpdateMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorUpdateMetadata) Reset() {
	*x = CollectorUpdateMetadata{}
	mi := &file_historian_historian_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorUpdateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorUpdateMetadata) ProtoMessage() {}

func (x *CollectorUpdateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorUpdateMetadata.ProtoReflect.Descriptor instead.
func (*CollectorUpdateMetadata) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{18}
}

func (x *CollectorUpdateMetadata) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *CollectorUpdateMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CollectorUpdateMetadata) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *CollectorUpdateMetadata) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_historian_historian_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{19}
}

func (x *File) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type MigrateMeasurementSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MeasurementUUID string                 `protobuf:"bytes,1,opt,name=measurementUUID,proto3" json:"measurementUUID,omitempty"`
	Settings        *structpb.Struct       `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MigrateMeasurementSettings) Reset() {
	*x = MigrateMeasurementSettings{}
	mi := &file_historian_historian_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateMeasurementSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateMeasurementSettings) ProtoMessage() {}

func (x *MigrateMeasurementSettings) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateMeasurementSettings.ProtoReflect.Descriptor instead.
func (*MigrateMeasurementSettings) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{20}
}

func (x *MigrateMeasurementSettings) GetMeasurementUUID() string {
	if x != nil {
		return x.MeasurementUUID
	}
	return ""
}

func (x *MigrateMeasurementSettings) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type MigrationRequest struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	Settings            *structpb.Struct              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	MeasurementSettings []*MigrateMeasurementSettings `protobuf:"bytes,2,rep,name=measurementSettings,proto3" json:"measurementSettings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MigrationRequest) Reset() {
	*x = MigrationRequest{}
	mi := &file_historian_historian_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationRequest) ProtoMessage() {}

func (x *MigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationRequest.ProtoReflect.Descriptor instead.
func (*MigrationRequest) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{21}
}

func (x *MigrationRequest) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *MigrationRequest) GetMeasurementSettings() []*MigrateMeasurementSettings {
	if x != nil {
		return x.MeasurementSettings
	}
	return nil
}

type HistorianInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistorianInfo) Reset() {
	*x = HistorianInfo{}
	mi := &file_historian_historian_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistorianInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistorianInfo) ProtoMessage() {}

func (x *HistorianInfo) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistorianInfo.ProtoReflect.Descriptor instead.
func (*HistorianInfo) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{22}
}

func (x *HistorianInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HistorianInfo) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type HealthUpdates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HealthUpdates []*HealthUpdate        `protobuf:"bytes,1,rep,name=healthUpdates,proto3" json:"healthUpdates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthUpdates) Reset() {
	*x = HealthUpdates{}
	mi := &file_historian_historian_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthUpdates) ProtoMessage() {}

func (x *HealthUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthUpdates.ProtoReflect.Descriptor instead.
func (*HealthUpdates) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{23}
}

func (x *HealthUpdates) GetHealthUpdates() []*HealthUpdate {
	if x != nil {
		return x.HealthUpdates
	}
	return nil
}

type HealthUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        string                 `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthUpdate) Reset() {
	*x = HealthUpdate{}
	mi := &file_historian_historian_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthUpdate) ProtoMessage() {}

func (x *HealthUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthUpdate.ProtoReflect.Descriptor instead.
func (*HealthUpdate) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{24}
}

func (x *HealthUpdate) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *HealthUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HealthUpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthUpdateReply) Reset() {
	*x = HealthUpdateReply{}
	mi := &file_historian_historian_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthUpdateReply) ProtoMessage() {}

func (x *HealthUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_historian_historian_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthUpdateReply.ProtoReflect.Descriptor instead.
func (*HealthUpdateReply) Descriptor() ([]byte, []int) {
	return file_historian_historian_proto_rawDescGZIP(), []int{25}
}

var File_historian_historian_proto protoreflect.FileDescriptor

const file_historian_historian_proto_rawDesc = "" +
	"\n" +
	"\x19historian/historian.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa7\x01\n" +
	"\vCollectorHA\x12,\n" +
	"\x11mainCollectorUUID\x18\x01 \x01(\tR\x11mainCollectorUUID\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1e\n" +
	"\n" +
	"healthPort\x18\x03 \x01(\x05R\n" +
	"healthPort\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x12\x1c\n" +
	"\tstopDelay\x18\x05 \x01(\x05R\tstopDelay\"\xb5\x03\n" +
	"\tCollector\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\fbuildversion\x18\x03 \x01(\tR\fbuildversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x123\n" +
	"\bsettings\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bsettings\x122\n" +
	"\n" +
	"haSettings\x18\a \x01(\v2\x12.proto.CollectorHAR\n" +
	"haSettings\x12\x18\n" +
	"\abuildOs\x18\b \x01(\tR\abuildOs\x12\x1c\n" +
	"\tbuildArch\x18\t \x01(\tR\tbuildArch\x12(\n" +
	"\x0fupdateAvailable\x18\n" +
	" \x01(\bR\x0fupdateAvailable\x12(\n" +
	"\x0fupdateToVersion\x18\v \x01(\tR\x0fupdateToVersion\x12-\n" +
	"\x05state\x18\f \x01(\v2\x17.google.protobuf.StructR\x05state\"\xb3\x02\n" +
	"\x17RegisterCollectorSchema\x12$\n" +
	"\rcollectorType\x18\x01 \x01(\tR\rcollectorType\x12\"\n" +
	"\fbuildVersion\x18\x02 \x01(\tR\fbuildVersion\x12U\n" +
	"\x19measurementSettingsSchema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x19measurementSettingsSchema\x12?\n" +
	"\x0esettingsSchema\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0esettingsSchema\x12\x18\n" +
	"\abuildOs\x18\x05 \x01(\tR\abuildOs\x12\x1c\n" +
	"\tbuildArch\x18\x06 \x01(\tR\tbuildArch\"\xde\x01\n" +
	"\x05Point\x12(\n" +
	"\x0fmeasurementUUID\x18\x01 \x01(\tR\x0fmeasurementUUID\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12+\n" +
	"\x04tags\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04tags\".\n" +
	"\x06Points\x12$\n" +
	"\x06points\x18\x01 \x03(\v2\f.proto.PointR\x06points\"\x13\n" +
	"\x11CreatePointsReply\"\xd7\x02\n" +
	"\vMeasurement\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x123\n" +
	"\bsettings\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bsettings\x12\x1a\n" +
	"\bdatatype\x18\a \x01(\tR\bdatatype\x12C\n" +
	"\x10engineeringSpecs\x18\b \x01(\v2\x17.proto.EngineeringSpecsR\x10engineeringSpecs\"\xe3\x01\n" +
	"\x10EngineeringSpecs\x12\x15\n" +
	"\x03uom\x18\x01 \x01(\tH\x00R\x03uom\x88\x01\x01\x12\x1f\n" +
	"\bvalueMin\x18\x02 \x01(\x01H\x01R\bvalueMin\x88\x01\x01\x12\x1f\n" +
	"\bvalueMax\x18\x03 \x01(\x01H\x02R\bvalueMax\x88\x01\x01\x12\x1d\n" +
	"\alimitLo\x18\x04 \x01(\x01H\x03R\alimitLo\x88\x01\x01\x12\x1d\n" +
	"\alimitHi\x18\x05 \x01(\x01H\x04R\alimitHi\x88\x01\x01B\x06\n" +
	"\x04_uomB\v\n" +
	"\t_valueMinB\v\n" +
	"\t_valueMaxB\n" +
	"\n" +
	"\b_limitLoB\n" +
	"\n" +
	"\b_limitHi\"l\n" +
	"\x12MeasurementRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12$\n" +
	"\rcollectorUUID\x18\x02 \x01(\tR\rcollectorUUID\"F\n" +
	"\fMeasurements\x126\n" +
	"\fmeasurements\x18\x01 \x03(\v2\x12.proto.MeasurementR\fmeasurements\"\xb7\x02\n" +
	"\x03Log\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.google.protobuf.StructR\amessage\x12&\n" +
	"\x05level\x18\x02 \x01(\x0e2\x10.proto.Log.LevelR\x05level\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\x06health\x18\x04 \x01(\tB\x02\x18\x01R\x06health\x12(\n" +
	"\x0fmeasurementUUID\x18\x05 \x01(\tR\x0fmeasurementUUID\"U\n" +
	"\x05Level\x12\t\n" +
	"\x05PANIC\x10\x00\x12\t\n" +
	"\x05FATAL\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\v\n" +
	"\aWARNING\x10\x03\x12\b\n" +
	"\x04INFO\x10\x04\x12\t\n" +
	"\x05DEBUG\x10\x05\x12\t\n" +
	"\x05TRACE\x10\x06\"&\n" +
	"\x04Logs\x12\x1e\n" +
	"\x04logs\x18\x01 \x03(\v2\n" +
	".proto.LogR\x04logs\"\x11\n" +
	"\x0fCreateLogsReply\"\xf5\x05\n" +
	"\n" +
	"Statistics\x12\"\n" +
	"\fsystemUptime\x18\x01 \x01(\x01R\fsystemUptime\x12&\n" +
	"\x0esystemCPUUsage\x18\x02 \x01(\x01R\x0esystemCPUUsage\x12,\n" +
	"\x11systemMemoryUsage\x18\x03 \x01(\x01R\x11systemMemoryUsage\x120\n" +
	"\x13systemFreeDiskSpace\x18\x04 \x01(\x03R\x13systemFreeDiskSpace\x12(\n" +
	"\x0fcollectorUptime\x18\x05 \x01(\x01R\x0fcollectorUptime\x120\n" +
	"\x13collectorPointsSent\x18\x06 \x01(\x03R\x13collectorPointsSent\x120\n" +
	"\x13collectorGoodPoints\x18\a \x01(\x03R\x13collectorGoodPoints\x12.\n" +
	"\x12collectorBadPoints\x18\b \x01(\x03R\x12collectorBadPoints\x12,\n" +
	"\x11bufferCurrentSize\x18\t \x01(\x03R\x11bufferCurrentSize\x12,\n" +
	"\x11bufferDiskFlushes\x18\n" +
	" \x01(\x03R\x11bufferDiskFlushes\x12*\n" +
	"\x10bufferErrorFiles\x18\v \x01(\x03R\x10bufferErrorFiles\x12-\n" +
	"\x05other\x18\f \x01(\v2\x17.google.protobuf.StructR\x05other\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\x14systemTotalDiskSpace\x18\x0e \x01(\x03R\x14systemTotalDiskSpace\x12*\n" +
	"\x10systemMemoryFree\x18\x0f \x01(\x03R\x10systemMemoryFree\x12,\n" +
	"\x11systemMemoryTotal\x18\x10 \x01(\x03R\x11systemMemoryTotal\"\x17\n" +
	"\x15CreateStatisticsReply\"\x19\n" +
	"\x17CreateMeasurementsReply\"\xc2\x02\n" +
	"\x11CreateMeasurement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\bdataType\x18\x02 \x01(\tH\x00R\bdataType\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\vautoOnboard\x18\x04 \x01(\bR\vautoOnboard\x12<\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x02R\n" +
	"attributes\x88\x01\x01\x128\n" +
	"\bsettings\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x03R\bsettings\x88\x01\x01B\v\n" +
	"\t_dataTypeB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_attributesB\v\n" +
	"\t_settings\"Y\n" +
	"\x19CreateMeasurementsRequest\x12<\n" +
	"\fmeasurements\x18\x01 \x03(\v2\x18.proto.CreateMeasurementR\fmeasurements\"q\n" +
	"\x17CollectorUpdateMetadata\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\"\x1c\n" +
	"\x04File\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"{\n" +
	"\x1aMigrateMeasurementSettings\x12(\n" +
	"\x0fmeasurementUUID\x18\x01 \x01(\tR\x0fmeasurementUUID\x123\n" +
	"\bsettings\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bsettings\"\x9c\x01\n" +
	"\x10MigrationRequest\x123\n" +
	"\bsettings\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bsettings\x12S\n" +
	"\x13measurementSettings\x18\x02 \x03(\v2!.proto.MigrateMeasurementSettingsR\x13measurementSettings\"I\n" +
	"\rHistorianInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\"J\n" +
	"\rHealthUpdates\x129\n" +
	"\rhealthUpdates\x18\x01 \x03(\v2\x13.proto.HealthUpdateR\rhealthUpdates\"`\n" +
	"\fHealthUpdate\x12\x16\n" +
	"\x06health\x18\x01 \x01(\tR\x06health\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x13\n" +
	"\x11HealthUpdateReply2\xec\a\n" +
	"\tHistorian\x128\n" +
	"\fGetCollector\x12\x16.google.protobuf.Empty\x1a\x10.proto.Collector\x12E\n" +
	"\x11RegisterCollector\x12\x1e.proto.RegisterCollectorSchema\x1a\x10.proto.Collector\x12?\n" +
	"\x12CreatePointsStream\x12\r.proto.Points\x1a\x18.proto.CreatePointsReply(\x01\x127\n" +
	"\fCreatePoints\x12\r.proto.Points\x1a\x18.proto.CreatePointsReply\x12A\n" +
	"\x0fGetMeasurements\x12\x19.proto.MeasurementRequest\x1a\x13.proto.Measurements\x12V\n" +
	"\x12CreateMeasurements\x12 .proto.CreateMeasurementsRequest\x1a\x1e.proto.CreateMeasurementsReply\x129\n" +
	"\x10CreateLogsStream\x12\v.proto.Logs\x1a\x16.proto.CreateLogsReply(\x01\x121\n" +
	"\n" +
	"CreateLogs\x12\v.proto.Logs\x1a\x16.proto.CreateLogsReply\x12K\n" +
	"\x16CreateStatisticsStream\x12\x11.proto.Statistics\x1a\x1c.proto.CreateStatisticsReply(\x01\x12C\n" +
	"\x10CreateStatistics\x12\x11.proto.Statistics\x1a\x1c.proto.CreateStatisticsReply\x12C\n" +
	"\x12GetCollectorUpdate\x12\x1e.proto.CollectorUpdateMetadata\x1a\v.proto.File0\x01\x12G\n" +
	"\x14UpdateCollectorState\x12\x17.google.protobuf.Struct\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fUpdateHealth\x12\x14.proto.HealthUpdates\x1a\x18.proto.HealthUpdateReply\x12B\n" +
	"\x0fMigrateSettings\x12\x17.proto.MigrationRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a\x14.proto.HistorianInfoB;Z9github.com/factrylabs/historian-proto/historian;historianb\x06proto3"

var (
	file_historian_historian_proto_rawDescOnce sync.Once
	file_historian_historian_proto_rawDescData []byte
)

func file_historian_historian_proto_rawDescGZIP() []byte {
	file_historian_historian_proto_rawDescOnce.Do(func() {
		file_historian_historian_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_historian_historian_proto_rawDesc), len(file_historian_historian_proto_rawDesc)))
	})
	return file_historian_historian_proto_rawDescData
}

var file_historian_historian_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_historian_historian_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_historian_historian_proto_goTypes = []any{
	(Log_Level)(0),                     // 0: proto.Log.Level
	(*CollectorHA)(nil),                // 1: proto.CollectorHA
	(*Collector)(nil),                  // 2: proto.Collector
	(*RegisterCollectorSchema)(nil),    // 3: proto.RegisterCollectorSchema
	(*Point)(nil),                      // 4: proto.Point
	(*Points)(nil),                     // 5: proto.Points
	(*CreatePointsReply)(nil),          // 6: proto.CreatePointsReply
	(*Measurement)(nil),                // 7: proto.Measurement
	(*EngineeringSpecs)(nil),           // 8: proto.EngineeringSpecs
	(*MeasurementRequest)(nil),         // 9: proto.MeasurementRequest
	(*Measurements)(nil),               // 10: proto.Measurements
	(*Log)(nil),                        // 11: proto.Log
	(*Logs)(nil),                       // 12: proto.Logs
	(*CreateLogsReply)(nil),            // 13: proto.CreateLogsReply
	(*Statistics)(nil),                 // 14: proto.Statistics
	(*CreateStatisticsReply)(nil),      // 15: proto.CreateStatisticsReply
	(*CreateMeasurementsReply)(nil),    // 16: proto.CreateMeasurementsReply
	(*CreateMeasurement)(nil),          // 17: proto.CreateMeasurement
	(*CreateMeasurementsRequest)(nil),  // 18: proto.CreateMeasurementsRequest
	(*CollectorUpdateMetadata)(nil),    // 19: proto.CollectorUpdateMetadata
	(*File)(nil),                       // 20: proto.File
	(*MigrateMeasurementSettings)(nil), // 21: proto.MigrateMeasurementSettings
	(*MigrationRequest)(nil),           // 22: proto.MigrationRequest
	(*HistorianInfo)(nil),              // 23: proto.HistorianInfo
	(*HealthUpdates)(nil),              // 24: proto.HealthUpdates
	(*HealthUpdate)(nil),               // 25: proto.HealthUpdate
	(*HealthUpdateReply)(nil),          // 26: proto.HealthUpdateReply
	(*structpb.Struct)(nil),            // 27: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 28: google.protobuf.Timestamp
	(*structpb.Value)(nil),             // 29: google.protobuf.Value
	(*emptypb.Empty)(nil),              // 30: google.protobuf.Empty
}
var file_historian_historian_proto_depIdxs = []int32{
	27, // 0: proto.Collector.settings:type_name -> google.protobuf.Struct
	1,  // 1: proto.Collector.haSettings:type_name -> proto.CollectorHA
	27, // 2: proto.Collector.state:type_name -> google.protobuf.Struct
	27, // 3: proto.RegisterCollectorSchema.measurementSettingsSchema:type_name -> google.protobuf.Struct
	27, // 4: proto.RegisterCollectorSchema.settingsSchema:type_name -> google.protobuf.Struct
	28, // 5: proto.Point.timestamp:type_name -> google.protobuf.Timestamp
	29, // 6: proto.Point.value:type_name -> google.protobuf.Value
	27, // 7: proto.Point.tags:type_name -> google.protobuf.Struct
	4,  // 8: proto.Points.points:type_name -> proto.Point
	28, // 9: proto.Measurement.createdAt:type_name -> google.protobuf.Timestamp
	28, // 10: proto.Measurement.updatedAt:type_name -> google.protobuf.Timestamp
	27, // 11: proto.Measurement.settings:type_name -> google.protobuf.Struct
	8,  // 12: proto.Measurement.engineeringSpecs:type_name -> proto.EngineeringSpecs
	28, // 13: proto.MeasurementRequest.since:type_name -> google.protobuf.Timestamp
	7,  // 14: proto.Measurements.measurements:type_name -> proto.Measurement
	27, // 15: proto.Log.message:type_name -> google.protobuf.Struct
	0,  // 16: proto.Log.level:type_name -> proto.Log.Level
	28, // 17: proto.Log.timestamp:type_name -> google.protobuf.Timestamp
	11, // 18: proto.Logs.logs:type_name -> proto.Log
	27, // 19: proto.Statistics.other:type_name -> google.protobuf.Struct
	28, // 20: proto.Statistics.timestamp:type_name -> google.protobuf.Timestamp
	27, // 21: proto.CreateMeasurement.attributes:type_name -> google.protobuf.Struct
	27, // 22: proto.CreateMeasurement.settings:type_name -> google.protobuf.Struct
	17, // 23: proto.CreateMeasurementsRequest.measurements:type_name -> proto.CreateMeasurement
	27, // 24: proto.MigrateMeasurementSettings.settings:type_name -> google.protobuf.Struct
	27, // 25: proto.MigrationRequest.settings:type_name -> google.protobuf.Struct
	21, // 26: proto.MigrationRequest.measurementSettings:type_name -> proto.MigrateMeasurementSettings
	25, // 27: proto.HealthUpdates.healthUpdates:type_name -> proto.HealthUpdate
	28, // 28: proto.HealthUpdate.timestamp:type_name -> google.protobuf.Timestamp
	30, // 29: proto.Historian.GetCollector:input_type -> google.protobuf.Empty
	3,  // 30: proto.Historian.RegisterCollector:input_type -> proto.RegisterCollectorSchema
	5,  // 31: proto.Historian.CreatePointsStream:input_type -> proto.Points
	5,  // 32: proto.Historian.CreatePoints:input_type -> proto.Points
	9,  // 33: proto.Historian.GetMeasurements:input_type -> proto.MeasurementRequest
	18, // 34: proto.Historian.CreateMeasurements:input_type -> proto.CreateMeasurementsRequest
	12, // 35: proto.Historian.CreateLogsStream:input_type -> proto.Logs
	12, // 36: proto.Historian.CreateLogs:input_type -> proto.Logs
	14, // 37: proto.Historian.CreateStatisticsStream:input_type -> proto.Statistics
	14, // 38: proto.Historian.CreateStatistics:input_type -> proto.Statistics
	19, // 39: proto.Historian.GetCollectorUpdate:input_type -> proto.CollectorUpdateMetadata
	27, // 40: proto.Historian.UpdateCollectorState:input_type -> google.protobuf.Struct
	24, // 41: proto.Historian.UpdateHealth:input_type -> proto.HealthUpdates
	22, // 42: proto.Historian.MigrateSettings:input_type -> proto.MigrationRequest
	30, // 43: proto.Historian.GetInfo:input_type -> google.protobuf.Empty
	2,  // 44: proto.Historian.GetCollector:output_type -> proto.Collector
	2,  // 45: proto.Historian.RegisterCollector:output_type -> proto.Collector
	6,  // 46: proto.Historian.CreatePointsStream:output_type -> proto.CreatePointsReply
	6,  // 47: proto.Historian.CreatePoints:output_type -> proto.CreatePointsReply
	10, // 48: proto.Historian.GetMeasurements:output_type -> proto.Measurements
	16, // 49: proto.Historian.CreateMeasurements:output_type -> proto.CreateMeasurementsReply
	13, // 50: proto.Historian.CreateLogsStream:output_type -> proto.CreateLogsReply
	13, // 51: proto.Historian.CreateLogs:output_type -> proto.CreateLogsReply
	15, // 52: proto.Historian.CreateStatisticsStream:output_type -> proto.CreateStatisticsReply
	15, // 53: proto.Historian.CreateStatistics:output_type -> proto.CreateStatisticsReply
	20, // 54: proto.Historian.GetCollectorUpdate:output_type -> proto.File
	30, // 55: proto.Historian.UpdateCollectorState:output_type -> google.protobuf.Empty
	26, // 56: proto.Historian.UpdateHealth:output_type -> proto.HealthUpdateReply
	30, // 57: proto.Historian.MigrateSettings:output_type -> google.protobuf.Empty
	23, // 58: proto.Historian.GetInfo:output_type -> proto.HistorianInfo
	44, // [44:59] is the sub-list for method output_type
	29, // [29:44] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_historian_historian_proto_init() }
func file_historian_historian_proto_init() {
	if File_historian_historian_proto != nil {
		return
	}
	file_historian_historian_proto_msgTypes[7].OneofWrappers = []any{}
	file_historian_historian_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_historian_historian_proto_rawDesc), len(file_historian_historian_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_historian_historian_proto_goTypes,
		DependencyIndexes: file_historian_historian_proto_depIdxs,
		EnumInfos:         file_historian_historian_proto_enumTypes,
		MessageInfos:      file_historian_historian_proto_msgTypes,
	}.Build()
	File_historian_historian_proto = out.File
	file_historian_historian_proto_goTypes = nil
	file_historian_historian_proto_depIdxs = nil
}
