// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: historian/historian.proto

package historian

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Historian_GetCollector_FullMethodName            = "/proto.Historian/GetCollector"
	Historian_RegisterCollector_FullMethodName       = "/proto.Historian/RegisterCollector"
	Historian_CreatePointsStream_FullMethodName      = "/proto.Historian/CreatePointsStream"
	Historian_CreatePoints_FullMethodName            = "/proto.Historian/CreatePoints"
	Historian_GetMeasurements_FullMethodName         = "/proto.Historian/GetMeasurements"
	Historian_CreateMeasurements_FullMethodName      = "/proto.Historian/CreateMeasurements"
	Historian_CreateLogsStream_FullMethodName        = "/proto.Historian/CreateLogsStream"
	Historian_CreateLogs_FullMethodName              = "/proto.Historian/CreateLogs"
	Historian_CreateStatisticsStream_FullMethodName  = "/proto.Historian/CreateStatisticsStream"
	Historian_CreateStatistics_FullMethodName        = "/proto.Historian/CreateStatistics"
	Historian_GetCollectorUpdate_FullMethodName      = "/proto.Historian/GetCollectorUpdate"
	Historian_UpdateCollectorState_FullMethodName    = "/proto.Historian/UpdateCollectorState"
	Historian_UpdateHealth_FullMethodName            = "/proto.Historian/UpdateHealth"
	Historian_MigrateSettings_FullMethodName         = "/proto.Historian/MigrateSettings"
	Historian_GetInfo_FullMethodName                 = "/proto.Historian/GetInfo"
	Historian_QueryTimeseries_FullMethodName         = "/proto.Historian/QueryTimeseries"
	Historian_GetAssets_FullMethodName               = "/proto.Historian/GetAssets"
	Historian_GetAssetProperties_FullMethodName      = "/proto.Historian/GetAssetProperties"
	Historian_GetMeasurementsByFilter_FullMethodName = "/proto.Historian/GetMeasurementsByFilter"
	Historian_GetCollectors_FullMethodName           = "/proto.Historian/GetCollectors"
	Historian_GetTimeseriesDatabases_FullMethodName  = "/proto.Historian/GetTimeseriesDatabases"
)

// HistorianClient is the client API for Historian service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The historian service definition.
// CollectorUUID gets passed in the header
type HistorianClient interface {
	GetCollector(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Collector, error)
	RegisterCollector(ctx context.Context, in *RegisterCollectorSchema, opts ...grpc.CallOption) (*Collector, error)
	CreatePointsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Points, CreatePointsReply], error)
	CreatePoints(ctx context.Context, in *Points, opts ...grpc.CallOption) (*CreatePointsReply, error)
	GetMeasurements(ctx context.Context, in *MeasurementRequest, opts ...grpc.CallOption) (*Measurements, error)
	CreateMeasurements(ctx context.Context, in *CreateMeasurementsRequest, opts ...grpc.CallOption) (*CreateMeasurementsReply, error)
	CreateLogsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Logs, CreateLogsReply], error)
	CreateLogs(ctx context.Context, in *Logs, opts ...grpc.CallOption) (*CreateLogsReply, error)
	CreateStatisticsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Statistics, CreateStatisticsReply], error)
	CreateStatistics(ctx context.Context, in *Statistics, opts ...grpc.CallOption) (*CreateStatisticsReply, error)
	GetCollectorUpdate(ctx context.Context, in *CollectorUpdateMetadata, opts ...grpc.CallOption) (grpc.ServerStreamingClient[File], error)
	UpdateCollectorState(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateHealth(ctx context.Context, in *HealthUpdates, opts ...grpc.CallOption) (*HealthUpdateReply, error)
	MigrateSettings(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HistorianInfo, error)
	QueryTimeseries(ctx context.Context, in *QueryTimeseriesRequest, opts ...grpc.CallOption) (*QueryTimeseriesResponse, error)
	GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*Assets, error)
	GetAssetProperties(ctx context.Context, in *GetAssetPropertiesRequest, opts ...grpc.CallOption) (*AssetProperties, error)
	GetMeasurementsByFilter(ctx context.Context, in *GetMeasurementsByFilterRequest, opts ...grpc.CallOption) (*Measurements, error)
	GetCollectors(ctx context.Context, in *GetCollectorsRequest, opts ...grpc.CallOption) (*Collectors, error)
	GetTimeseriesDatabases(ctx context.Context, in *GetTimeseriesDatabasesRequest, opts ...grpc.CallOption) (*TimeseriesDatabases, error)
}

type historianClient struct {
	cc grpc.ClientConnInterface
}

func NewHistorianClient(cc grpc.ClientConnInterface) HistorianClient {
	return &historianClient{cc}
}

func (c *historianClient) GetCollector(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Collector, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Collector)
	err := c.cc.Invoke(ctx, Historian_GetCollector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) RegisterCollector(ctx context.Context, in *RegisterCollectorSchema, opts ...grpc.CallOption) (*Collector, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Collector)
	err := c.cc.Invoke(ctx, Historian_RegisterCollector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) CreatePointsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Points, CreatePointsReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Historian_ServiceDesc.Streams[0], Historian_CreatePointsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Points, CreatePointsReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Historian_CreatePointsStreamClient = grpc.ClientStreamingClient[Points, CreatePointsReply]

func (c *historianClient) CreatePoints(ctx context.Context, in *Points, opts ...grpc.CallOption) (*CreatePointsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePointsReply)
	err := c.cc.Invoke(ctx, Historian_CreatePoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) GetMeasurements(ctx context.Context, in *MeasurementRequest, opts ...grpc.CallOption) (*Measurements, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Measurements)
	err := c.cc.Invoke(ctx, Historian_GetMeasurements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) CreateMeasurements(ctx context.Context, in *CreateMeasurementsRequest, opts ...grpc.CallOption) (*CreateMeasurementsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMeasurementsReply)
	err := c.cc.Invoke(ctx, Historian_CreateMeasurements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) CreateLogsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Logs, CreateLogsReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Historian_ServiceDesc.Streams[1], Historian_CreateLogsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Logs, CreateLogsReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Historian_CreateLogsStreamClient = grpc.ClientStreamingClient[Logs, CreateLogsReply]

func (c *historianClient) CreateLogs(ctx context.Context, in *Logs, opts ...grpc.CallOption) (*CreateLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLogsReply)
	err := c.cc.Invoke(ctx, Historian_CreateLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) CreateStatisticsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Statistics, CreateStatisticsReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Historian_ServiceDesc.Streams[2], Historian_CreateStatisticsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Statistics, CreateStatisticsReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Historian_CreateStatisticsStreamClient = grpc.ClientStreamingClient[Statistics, CreateStatisticsReply]

func (c *historianClient) CreateStatistics(ctx context.Context, in *Statistics, opts ...grpc.CallOption) (*CreateStatisticsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStatisticsReply)
	err := c.cc.Invoke(ctx, Historian_CreateStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) GetCollectorUpdate(ctx context.Context, in *CollectorUpdateMetadata, opts ...grpc.CallOption) (grpc.ServerStreamingClient[File], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Historian_ServiceDesc.Streams[3], Historian_GetCollectorUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CollectorUpdateMetadata, File]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Historian_GetCollectorUpdateClient = grpc.ServerStreamingClient[File]

func (c *historianClient) UpdateCollectorState(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Historian_UpdateCollectorState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) UpdateHealth(ctx context.Context, in *HealthUpdates, opts ...grpc.CallOption) (*HealthUpdateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthUpdateReply)
	err := c.cc.Invoke(ctx, Historian_UpdateHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) MigrateSettings(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Historian_MigrateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HistorianInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistorianInfo)
	err := c.cc.Invoke(ctx, Historian_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) QueryTimeseries(ctx context.Context, in *QueryTimeseriesRequest, opts ...grpc.CallOption) (*QueryTimeseriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTimeseriesResponse)
	err := c.cc.Invoke(ctx, Historian_QueryTimeseries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*Assets, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assets)
	err := c.cc.Invoke(ctx, Historian_GetAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) GetAssetProperties(ctx context.Context, in *GetAssetPropertiesRequest, opts ...grpc.CallOption) (*AssetProperties, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetProperties)
	err := c.cc.Invoke(ctx, Historian_GetAssetProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) GetMeasurementsByFilter(ctx context.Context, in *GetMeasurementsByFilterRequest, opts ...grpc.CallOption) (*Measurements, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Measurements)
	err := c.cc.Invoke(ctx, Historian_GetMeasurementsByFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) GetCollectors(ctx context.Context, in *GetCollectorsRequest, opts ...grpc.CallOption) (*Collectors, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Collectors)
	err := c.cc.Invoke(ctx, Historian_GetCollectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historianClient) GetTimeseriesDatabases(ctx context.Context, in *GetTimeseriesDatabasesRequest, opts ...grpc.CallOption) (*TimeseriesDatabases, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeseriesDatabases)
	err := c.cc.Invoke(ctx, Historian_GetTimeseriesDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistorianServer is the server API for Historian service.
// All implementations must embed UnimplementedHistorianServer
// for forward compatibility.
//
// The historian service definition.
// CollectorUUID gets passed in the header
type HistorianServer interface {
	GetCollector(context.Context, *emptypb.Empty) (*Collector, error)
	RegisterCollector(context.Context, *RegisterCollectorSchema) (*Collector, error)
	CreatePointsStream(grpc.ClientStreamingServer[Points, CreatePointsReply]) error
	CreatePoints(context.Context, *Points) (*CreatePointsReply, error)
	GetMeasurements(context.Context, *MeasurementRequest) (*Measurements, error)
	CreateMeasurements(context.Context, *CreateMeasurementsRequest) (*CreateMeasurementsReply, error)
	CreateLogsStream(grpc.ClientStreamingServer[Logs, CreateLogsReply]) error
	CreateLogs(context.Context, *Logs) (*CreateLogsReply, error)
	CreateStatisticsStream(grpc.ClientStreamingServer[Statistics, CreateStatisticsReply]) error
	CreateStatistics(context.Context, *Statistics) (*CreateStatisticsReply, error)
	GetCollectorUpdate(*CollectorUpdateMetadata, grpc.ServerStreamingServer[File]) error
	UpdateCollectorState(context.Context, *structpb.Struct) (*emptypb.Empty, error)
	UpdateHealth(context.Context, *HealthUpdates) (*HealthUpdateReply, error)
	MigrateSettings(context.Context, *MigrationRequest) (*emptypb.Empty, error)
	GetInfo(context.Context, *emptypb.Empty) (*HistorianInfo, error)
	QueryTimeseries(context.Context, *QueryTimeseriesRequest) (*QueryTimeseriesResponse, error)
	GetAssets(context.Context, *GetAssetsRequest) (*Assets, error)
	GetAssetProperties(context.Context, *GetAssetPropertiesRequest) (*AssetProperties, error)
	GetMeasurementsByFilter(context.Context, *GetMeasurementsByFilterRequest) (*Measurements, error)
	GetCollectors(context.Context, *GetCollectorsRequest) (*Collectors, error)
	GetTimeseriesDatabases(context.Context, *GetTimeseriesDatabasesRequest) (*TimeseriesDatabases, error)
	mustEmbedUnimplementedHistorianServer()
}

// UnimplementedHistorianServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistorianServer struct{}

func (UnimplementedHistorianServer) GetCollector(context.Context, *emptypb.Empty) (*Collector, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollector not implemented")
}
func (UnimplementedHistorianServer) RegisterCollector(context.Context, *RegisterCollectorSchema) (*Collector, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCollector not implemented")
}
func (UnimplementedHistorianServer) CreatePointsStream(grpc.ClientStreamingServer[Points, CreatePointsReply]) error {
	return status.Errorf(codes.Unimplemented, "method CreatePointsStream not implemented")
}
func (UnimplementedHistorianServer) CreatePoints(context.Context, *Points) (*CreatePointsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePoints not implemented")
}
func (UnimplementedHistorianServer) GetMeasurements(context.Context, *MeasurementRequest) (*Measurements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeasurements not implemented")
}
func (UnimplementedHistorianServer) CreateMeasurements(context.Context, *CreateMeasurementsRequest) (*CreateMeasurementsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMeasurements not implemented")
}
func (UnimplementedHistorianServer) CreateLogsStream(grpc.ClientStreamingServer[Logs, CreateLogsReply]) error {
	return status.Errorf(codes.Unimplemented, "method CreateLogsStream not implemented")
}
func (UnimplementedHistorianServer) CreateLogs(context.Context, *Logs) (*CreateLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLogs not implemented")
}
func (UnimplementedHistorianServer) CreateStatisticsStream(grpc.ClientStreamingServer[Statistics, CreateStatisticsReply]) error {
	return status.Errorf(codes.Unimplemented, "method CreateStatisticsStream not implemented")
}
func (UnimplementedHistorianServer) CreateStatistics(context.Context, *Statistics) (*CreateStatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStatistics not implemented")
}
func (UnimplementedHistorianServer) GetCollectorUpdate(*CollectorUpdateMetadata, grpc.ServerStreamingServer[File]) error {
	return status.Errorf(codes.Unimplemented, "method GetCollectorUpdate not implemented")
}
func (UnimplementedHistorianServer) UpdateCollectorState(context.Context, *structpb.Struct) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollectorState not implemented")
}
func (UnimplementedHistorianServer) UpdateHealth(context.Context, *HealthUpdates) (*HealthUpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHealth not implemented")
}
func (UnimplementedHistorianServer) MigrateSettings(context.Context, *MigrationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateSettings not implemented")
}
func (UnimplementedHistorianServer) GetInfo(context.Context, *emptypb.Empty) (*HistorianInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedHistorianServer) QueryTimeseries(context.Context, *QueryTimeseriesRequest) (*QueryTimeseriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTimeseries not implemented")
}
func (UnimplementedHistorianServer) GetAssets(context.Context, *GetAssetsRequest) (*Assets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssets not implemented")
}
func (UnimplementedHistorianServer) GetAssetProperties(context.Context, *GetAssetPropertiesRequest) (*AssetProperties, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetProperties not implemented")
}
func (UnimplementedHistorianServer) GetMeasurementsByFilter(context.Context, *GetMeasurementsByFilterRequest) (*Measurements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeasurementsByFilter not implemented")
}
func (UnimplementedHistorianServer) GetCollectors(context.Context, *GetCollectorsRequest) (*Collectors, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectors not implemented")
}
func (UnimplementedHistorianServer) GetTimeseriesDatabases(context.Context, *GetTimeseriesDatabasesRequest) (*TimeseriesDatabases, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeseriesDatabases not implemented")
}
func (UnimplementedHistorianServer) mustEmbedUnimplementedHistorianServer() {}
func (UnimplementedHistorianServer) testEmbeddedByValue()                   {}

// UnsafeHistorianServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistorianServer will
// result in compilation errors.
type UnsafeHistorianServer interface {
	mustEmbedUnimplementedHistorianServer()
}

func RegisterHistorianServer(s grpc.ServiceRegistrar, srv HistorianServer) {
	// If the following call pancis, it indicates UnimplementedHistorianServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Historian_ServiceDesc, srv)
}

func _Historian_GetCollector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).GetCollector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_GetCollector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).GetCollector(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_RegisterCollector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCollectorSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).RegisterCollector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_RegisterCollector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).RegisterCollector(ctx, req.(*RegisterCollectorSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_CreatePointsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HistorianServer).CreatePointsStream(&grpc.GenericServerStream[Points, CreatePointsReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Historian_CreatePointsStreamServer = grpc.ClientStreamingServer[Points, CreatePointsReply]

func _Historian_CreatePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Points)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).CreatePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_CreatePoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).CreatePoints(ctx, req.(*Points))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_GetMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).GetMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_GetMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).GetMeasurements(ctx, req.(*MeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_CreateMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeasurementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).CreateMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_CreateMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).CreateMeasurements(ctx, req.(*CreateMeasurementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_CreateLogsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HistorianServer).CreateLogsStream(&grpc.GenericServerStream[Logs, CreateLogsReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Historian_CreateLogsStreamServer = grpc.ClientStreamingServer[Logs, CreateLogsReply]

func _Historian_CreateLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Logs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).CreateLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_CreateLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).CreateLogs(ctx, req.(*Logs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_CreateStatisticsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HistorianServer).CreateStatisticsStream(&grpc.GenericServerStream[Statistics, CreateStatisticsReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Historian_CreateStatisticsStreamServer = grpc.ClientStreamingServer[Statistics, CreateStatisticsReply]

func _Historian_CreateStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Statistics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).CreateStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_CreateStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).CreateStatistics(ctx, req.(*Statistics))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_GetCollectorUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectorUpdateMetadata)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HistorianServer).GetCollectorUpdate(m, &grpc.GenericServerStream[CollectorUpdateMetadata, File]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Historian_GetCollectorUpdateServer = grpc.ServerStreamingServer[File]

func _Historian_UpdateCollectorState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).UpdateCollectorState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_UpdateCollectorState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).UpdateCollectorState(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_UpdateHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).UpdateHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_UpdateHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).UpdateHealth(ctx, req.(*HealthUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_MigrateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).MigrateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_MigrateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).MigrateSettings(ctx, req.(*MigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).GetInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_QueryTimeseries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTimeseriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).QueryTimeseries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_QueryTimeseries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).QueryTimeseries(ctx, req.(*QueryTimeseriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_GetAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).GetAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_GetAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).GetAssets(ctx, req.(*GetAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_GetAssetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).GetAssetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_GetAssetProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).GetAssetProperties(ctx, req.(*GetAssetPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_GetMeasurementsByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeasurementsByFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).GetMeasurementsByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_GetMeasurementsByFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).GetMeasurementsByFilter(ctx, req.(*GetMeasurementsByFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_GetCollectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).GetCollectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_GetCollectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).GetCollectors(ctx, req.(*GetCollectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Historian_GetTimeseriesDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeseriesDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianServer).GetTimeseriesDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Historian_GetTimeseriesDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianServer).GetTimeseriesDatabases(ctx, req.(*GetTimeseriesDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Historian_ServiceDesc is the grpc.ServiceDesc for Historian service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Historian_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Historian",
	HandlerType: (*HistorianServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCollector",
			Handler:    _Historian_GetCollector_Handler,
		},
		{
			MethodName: "RegisterCollector",
			Handler:    _Historian_RegisterCollector_Handler,
		},
		{
			MethodName: "CreatePoints",
			Handler:    _Historian_CreatePoints_Handler,
		},
		{
			MethodName: "GetMeasurements",
			Handler:    _Historian_GetMeasurements_Handler,
		},
		{
			MethodName: "CreateMeasurements",
			Handler:    _Historian_CreateMeasurements_Handler,
		},
		{
			MethodName: "CreateLogs",
			Handler:    _Historian_CreateLogs_Handler,
		},
		{
			MethodName: "CreateStatistics",
			Handler:    _Historian_CreateStatistics_Handler,
		},
		{
			MethodName: "UpdateCollectorState",
			Handler:    _Historian_UpdateCollectorState_Handler,
		},
		{
			MethodName: "UpdateHealth",
			Handler:    _Historian_UpdateHealth_Handler,
		},
		{
			MethodName: "MigrateSettings",
			Handler:    _Historian_MigrateSettings_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Historian_GetInfo_Handler,
		},
		{
			MethodName: "QueryTimeseries",
			Handler:    _Historian_QueryTimeseries_Handler,
		},
		{
			MethodName: "GetAssets",
			Handler:    _Historian_GetAssets_Handler,
		},
		{
			MethodName: "GetAssetProperties",
			Handler:    _Historian_GetAssetProperties_Handler,
		},
		{
			MethodName: "GetMeasurementsByFilter",
			Handler:    _Historian_GetMeasurementsByFilter_Handler,
		},
		{
			MethodName: "GetCollectors",
			Handler:    _Historian_GetCollectors_Handler,
		},
		{
			MethodName: "GetTimeseriesDatabases",
			Handler:    _Historian_GetTimeseriesDatabases_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreatePointsStream",
			Handler:       _Historian_CreatePointsStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateLogsStream",
			Handler:       _Historian_CreateLogsStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateStatisticsStream",
			Handler:       _Historian_CreateStatisticsStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetCollectorUpdate",
			Handler:       _Historian_GetCollectorUpdate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "historian/historian.proto",
}
